import { Connection, PublicKey, SystemProgram } from "@solana/web3.js";
import { Program, AnchorProvider, BN, Idl } from "@coral-xyz/anchor";
// @ts-ignore - Temporary until official types are correctly exported
import { Curve, Hash, SignatureAlgorithm } from "@ika.xyz/sdk";
import {
  VaultState,
  CollateralPosition,
  ChainAsset,
  CHAIN_ASSET_LABELS,
  CHAIN_ASSET_DECIMALS,
} from "./types.js";
import { getChainCryptoConfig, IkaClient, createDevnetIkaClient } from "./ika-client.js";

// ---------------------------------------------------------------------------
// IDL + Program ID
// ---------------------------------------------------------------------------

// The collateral-vault program ID — updated by `anchor build`
const COLLATERAL_VAULT_PROGRAM_ID = new PublicKey(
  "4jJrbTHiAP5ocWhbUqJG6m1bQ6cRkNi7vJvHWpRABwBm"
);

// ---------------------------------------------------------------------------
// PDA Derivation
// ---------------------------------------------------------------------------

/**
 * Derives the VaultAccount PDA for a given owner.
 * Seeds: [b"vault", owner.toBytes()]
 */
function deriveVaultPda(
  owner: PublicKey,
  programId: PublicKey = COLLATERAL_VAULT_PROGRAM_ID
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), owner.toBuffer()],
    programId
  );
}

// ---------------------------------------------------------------------------
// Helper: load program from provider
// ---------------------------------------------------------------------------

/**
 * Loads the collateral_vault Anchor program. In a real deployment, the IDL
 * would be fetched from the chain or imported from a generated file. Here
 * we construct it inline to match the on-chain program exactly.
 */
function getProgram(provider: AnchorProvider): Program {
  // The IDL is auto-generated by `anchor build` into
  // target/idl/collateral_vault.json. At runtime we load it dynamically.
  // For Phase 1, we construct the Program instance using the workspace
  // pattern that @coral-xyz/anchor provides.
  //
  // In the test harness and scripts this is accessed via:
  //   const program = anchor.workspace.CollateralVault as Program;
  //
  // For the SDK, we accept any IDL-compatible Program.
  // This function is a convenience wrapper.

  // eslint-disable-next-line @typescript-eslint/no-var-requires
  let idl: Idl;
  try {
    // When running in the monorepo after `anchor build`, the IDL exists here
    idl = require("../../target/idl/collateral_vault.json");
  } catch {
    throw new Error(
      "IDL not found. Run `anchor build` first to generate target/idl/collateral_vault.json"
    );
  }

  return new Program(idl, provider);
}

// ---------------------------------------------------------------------------
// Exported Functions
// ---------------------------------------------------------------------------

/**
 * Initializes a new collateral vault for the connected wallet.
 *
 * @param provider    - AnchorProvider with the user's wallet as signer
 * @param ltvBps      - Loan-to-value ratio in basis points (max 8000)
 * @param liquidationThresholdBps - Liquidation threshold in bps (max 9000)
 * @param oracleAuthority - Public key of the oracle/relayer that will record deposits
 * @returns The vault PDA and transaction signature
 */
export async function initializeVault(
  provider: AnchorProvider,
  ltvBps: number,
  liquidationThresholdBps: number,
  oracleAuthority: PublicKey
): Promise<{ vaultPda: PublicKey; txSig: string }> {
  const program = getProgram(provider);
  const user = provider.wallet.publicKey;
  const [vaultPda] = deriveVaultPda(user, program.programId);

  const txSig = await program.methods
    .initializeVault(ltvBps, liquidationThresholdBps)
    .accounts({
      vault: vaultPda,
      user: user,
      oracleAuthority: oracleAuthority,
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  return { vaultPda, txSig };
}

/**
 * Creates an Ika dWallet for the specified chain and registers it on-chain.
 *
 * Flow:
 * 1. Determine cryptographic primitives (Curve, Hash, SignatureAlgorithm) per chain
 * 2. Call Ika SDK to create a zero-trust dWallet via DKG
 * 3. Transfer dWallet authority to the vault PDA
 * 4. Call register_dwallet on-chain to bind the dWallet to the vault
 *
 * @param provider - AnchorProvider with the user's wallet
 * @param chain    - ChainAsset enum value
 * @param vaultPda - The user's vault PDA
 * @returns The dWallet ID bytes and on-chain registration tx signature
 */
export async function createAndRegisterDWallet(
  provider: AnchorProvider,
  chain: ChainAsset,
  vaultPda: PublicKey
): Promise<{ dwalletId: Uint8Array; txSig: string }> {
  const program = getProgram(provider);
  const user = provider.wallet.publicKey;
  const cryptoConfig = getChainCryptoConfig(chain);

  // --- Step 1: Create dWallet via Ika SDK ---
  // [IKA-VERIFY: The exact SDK API for DKG may differ from this pattern.
  // Verify against the latest @ika.xyz/sdk documentation.]
  const ikaClient = createDevnetIkaClient(provider.connection);

  let dwalletId: Uint8Array;
  try {
    const result = await ikaClient.createDwallet(chain, user);
    dwalletId = result.dwalletId;
  } catch (e) {
    // During development, generate a deterministic placeholder ID
    // This allows the on-chain registration flow to be tested end-to-end
    // before the Ika SDK DKG is fully functional.
    console.warn(
      `[IKA-VERIFY] dWallet creation not yet available, using deterministic ID for chain=${chain}`
    );
    const encoder = new TextEncoder();
    const seed = encoder.encode(`dwallet-${chain}-${user.toBase58()}`);
    dwalletId = new Uint8Array(32);
    for (let i = 0; i < 32; i++) {
      dwalletId[i] = seed[i % seed.length];
    }
  }

  // --- Step 2: Transfer authority to vault PDA ---
  // [IKA-VERIFY: The authority transfer mechanism may be a Sui transaction
  // or a Solana instruction. Verify the exact flow with Ika pre-alpha docs.]
  try {
    await ikaClient.transferAuthorityToPda(dwalletId, vaultPda);
  } catch (e) {
    console.warn("[IKA-VERIFY] Authority transfer not yet available, skipping");
  }

  // --- Step 3: Register on-chain ---
  // Map ChainAsset enum to chain/asset bytes for the program
  const chainByte = chainAssetToChainByte(chain);
  const assetByte = chain as number; // asset index matches ChainAsset enum

  const dwalletIdArray = Array.from(dwalletId);
  const txSig = await program.methods
    .registerDwallet(dwalletIdArray, chainByte, assetByte)
    .accounts({
      vault: vaultPda,
      user: user,
    })
    .rpc();

  return { dwalletId, txSig };
}

/**
 * Records a deposit confirmed by the oracle/relayer.
 *
 * @param provider      - AnchorProvider with the oracle authority's wallet
 * @param vaultPda      - The vault PDA to deposit into
 * @param dwalletId     - The 32-byte dWallet ID
 * @param rawAmount     - Amount in native asset denomination
 * @param usdPrice6Dec  - USD price with 6 decimal precision
 * @returns Transaction signature
 */
export async function recordDeposit(
  provider: AnchorProvider,
  vaultPda: PublicKey,
  dwalletId: Uint8Array,
  rawAmount: BN,
  usdPrice6Dec: BN
): Promise<string> {
  const program = getProgram(provider);
  const oracleAuthority = provider.wallet.publicKey;

  const txSig = await program.methods
    .recordDeposit(Array.from(dwalletId), rawAmount, usdPrice6Dec)
    .accounts({
      vault: vaultPda,
      oracleAuthority: oracleAuthority,
    })
    .rpc();

  return txSig;
}

/**
 * Fetches and maps the on-chain VaultAccount into a typed VaultState.
 *
 * @param provider - AnchorProvider for RPC access
 * @param owner    - The vault owner's public key
 * @returns Fully populated VaultState with health factor
 */
export async function getVaultState(
  provider: AnchorProvider,
  owner: PublicKey
): Promise<VaultState> {
  const program = getProgram(provider);
  const [vaultPda] = deriveVaultPda(owner, program.programId);

  const vaultAccount = await (program.account as any).vaultAccount.fetch(vaultPda);

  // Map only active positions (first numPositions entries from fixed array)
  const numPositions = vaultAccount.numPositions as number;
  const allPositions = vaultAccount.positions as any[];
  const activePositions = allPositions.slice(0, numPositions);

  const positions: CollateralPosition[] = activePositions.map((p: any) => {
    const chainAsset = chainByteToChainAsset(p.chain);
    const healthFactor =
      vaultAccount.usedCreditUsd && (vaultAccount.usedCreditUsd as BN).gtn(0)
        ? new BN(p.usdValue)
            .mul(new BN(10_000))
            .div(vaultAccount.usedCreditUsd as BN)
        : new BN("18446744073709551615"); // u64::MAX

    return {
      chain: chainAsset,
      asset: CHAIN_ASSET_LABELS[chainAsset] ?? `Asset(${p.asset})`,
      amount: new BN(p.rawAmount),
      dwalletId: Buffer.from(p.dwalletId).toString("hex"),
      healthFactor,
      valueUsd: new BN(p.usdValue),
      isLiquidatable: false,
    };
  });

  // Calculate portfolio-level metrics
  const totalCollateralUsd = new BN(vaultAccount.totalCollateralUsd as any);
  const usedCreditUsd = new BN(vaultAccount.usedCreditUsd as any);

  const utilizationBps = usedCreditUsd.gtn(0)
    ? totalCollateralUsd.mul(new BN(10_000)).div(usedCreditUsd).toNumber()
    : 0;

  const availableCredit = totalCollateralUsd
    .mul(new BN(vaultAccount.ltvBps as number))
    .div(new BN(10_000))
    .sub(usedCreditUsd);

  return {
    totalCollateralUsd,
    availableCredit: availableCredit.gtn(0) ? availableCredit : new BN(0),
    utilizationBps,
    positions,
    activeOrderCount: 0, // Populated by ciphervault-core in Phase 2
  };
}

/**
 * Returns the health factor as a human-readable ratio.
 * e.g., 1.45 means 145% collateralization.
 *
 * @param provider - AnchorProvider for RPC access
 * @param owner    - The vault owner's public key
 * @returns Health factor as a float (Infinity if no credit used)
 */
export async function getHealthFactor(
  provider: AnchorProvider,
  owner: PublicKey
): Promise<number> {
  const program = getProgram(provider);
  const [vaultPda] = deriveVaultPda(owner, program.programId);

  const vaultAccount = await (program.account as any).vaultAccount.fetch(vaultPda);

  const usedCredit = new BN(vaultAccount.usedCreditUsd as any);
  if (usedCredit.isZero()) {
    return Infinity;
  }

  const totalCollateral = new BN(vaultAccount.totalCollateralUsd as any);
  // health = totalCollateral / usedCredit (as a ratio, not bps)
  const healthBps = totalCollateral.mul(new BN(10_000)).div(usedCredit);
  return healthBps.toNumber() / 10_000;
}

/**
 * Watches for CollateralDeposited events on a specific vault.
 *
 * Uses connection.onLogs to subscribe to program log events and parses
 * the Anchor event discriminator for CollateralDeposited.
 *
 * @param connection - Solana Connection (must support websocket subscriptions)
 * @param vaultPda   - The vault PDA to monitor
 * @param onDeposit  - Callback invoked with the deposit details
 * @returns Unsubscribe function to stop watching
 */
export function watchForDeposit(
  connection: Connection,
  vaultPda: PublicKey,
  onDeposit: (position: CollateralPosition) => void
): () => void {
  const subscriptionId = connection.onLogs(
    COLLATERAL_VAULT_PROGRAM_ID,
    (logs) => {
      // Check if this log set mentions our vault
      const mentionsVault = logs.logs.some((log) =>
        log.includes(vaultPda.toBase58())
      );

      // Look for CollateralDeposited event in the logs
      const hasDepositEvent = logs.logs.some((log) =>
        log.includes("CollateralDeposited")
      );

      if (hasDepositEvent) {
        // Parse the event data from the log lines.
        // Anchor emits events as base64-encoded borsh data prefixed with
        // "Program data: <base64>". In production you'd decode the full
        // borsh event. For Phase 1, we emit a synthetic position update
        // that the UI can react to.
        const position: CollateralPosition = {
          chain: ChainAsset.BtcNative,
          asset: "BTC",
          amount: new BN(0),
          dwalletId: "",
          healthFactor: new BN("18446744073709551615"),
          valueUsd: new BN(0),
          isLiquidatable: false,
        };

        // Extract amounts from log lines if possible
        for (const line of logs.logs) {
          if (line.includes("Program data:")) {
            // In a full implementation, decode the base64 borsh payload here.
            // For now, trigger the callback so the UI knows a deposit occurred.
            onDeposit(position);
            return;
          }
        }

        // Fallback: still notify even if we couldn't parse the exact data
        onDeposit(position);
      }
    },
    "confirmed"
  );

  // Return unsubscribe function
  return () => {
    connection.removeOnLogsListener(subscriptionId);
  };
}

// ---------------------------------------------------------------------------
// Internal Helpers
// ---------------------------------------------------------------------------

/**
 * Maps a ChainAsset enum value to the chain byte used by the on-chain program.
 * 0=BTC, 1=ETH, 2=SOL, 3=RWA
 */
function chainAssetToChainByte(chain: ChainAsset): number {
  switch (chain) {
    case ChainAsset.BtcNative:
      return 0;
    case ChainAsset.EthNative:
      return 1;
    case ChainAsset.SolNative:
      return 2;
    case ChainAsset.Usdc:
    case ChainAsset.TokenizedTBill:
    case ChainAsset.TokenizedRealEstate:
    case ChainAsset.TokenizedGold:
      return 3; // RWA bucket
    default:
      return 0;
  }
}

/**
 * Maps an on-chain chain byte back to the ChainAsset enum.
 */
function chainByteToChainAsset(chainByte: number): ChainAsset {
  switch (chainByte) {
    case 0:
      return ChainAsset.BtcNative;
    case 1:
      return ChainAsset.EthNative;
    case 2:
      return ChainAsset.SolNative;
    case 3:
      return ChainAsset.Usdc; // Default RWA to USDC bucket
    default:
      return ChainAsset.BtcNative;
  }
}

// Re-export for convenience
export { deriveVaultPda, COLLATERAL_VAULT_PROGRAM_ID };
